//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вакансии.
    /// </summary>
    // *** Start programmer edit section *** (Вакансии CustomAttributes)

    // *** End programmer edit section *** (Вакансии CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВакансииE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("ВакансииL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Вакансии : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Вакансии CustomMembers)

        // *** End programmer edit section *** (Вакансии CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Вакансии.Наименование CustomAttributes)

        // *** End programmer edit section *** (Вакансии.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Вакансии.Наименование Get start)

                // *** End programmer edit section *** (Вакансии.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Вакансии.Наименование Get end)

                // *** End programmer edit section *** (Вакансии.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Вакансии.Наименование Set start)

                // *** End programmer edit section *** (Вакансии.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Вакансии.Наименование Set end)

                // *** End programmer edit section *** (Вакансии.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВакансииE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВакансииE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВакансииE", typeof(IIS.KR.Вакансии));
                }
            }
            
            /// <summary>
            /// "ВакансииL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВакансииL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВакансииL", typeof(IIS.KR.Вакансии));
                }
            }
        }
    }
}
