//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид договора.
    /// </summary>
    // *** Start programmer edit section *** (ВидДоговора CustomAttributes)

    // *** End programmer edit section *** (ВидДоговора CustomAttributes)
    public enum ВидДоговора
    {
        
        // *** Start programmer edit section *** (ВидДоговора.Срочный CustomAttributes)

        // *** End programmer edit section *** (ВидДоговора.Срочный CustomAttributes)
        [Caption("Срочный")]
        Срочный,
        
        // *** Start programmer edit section *** (ВидДоговора.Бессрочный CustomAttributes)

        // *** End programmer edit section *** (ВидДоговора.Бессрочный CustomAttributes)
        [Caption("Бессрочный")]
        Бессрочный,
    }
}
