//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Вид образование.
    /// </summary>
    // *** Start programmer edit section *** (ВидОбразование CustomAttributes)

    // *** End programmer edit section *** (ВидОбразование CustomAttributes)
    public enum ВидОбразование
    {
        
        // *** Start programmer edit section *** (ВидОбразование.Высшее CustomAttributes)

        // *** End programmer edit section *** (ВидОбразование.Высшее CustomAttributes)
        [Caption("Высшее")]
        Высшее,
        
        // *** Start programmer edit section *** (ВидОбразование.СПО CustomAttributes)

        // *** End programmer edit section *** (ВидОбразование.СПО CustomAttributes)
        [Caption("СПО")]
        СПО,
        
        // *** Start programmer edit section *** (ВидОбразование.Школа CustomAttributes)

        // *** End programmer edit section *** (ВидОбразование.Школа CustomAttributes)
        [Caption("Школа")]
        Школа,
    }
}
