//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// График.
    /// </summary>
    // *** Start programmer edit section *** (График CustomAttributes)

    // *** End programmer edit section *** (График CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГрафикE", new string[] {
            "Дата as \'Дата\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.Должность as \'Должность\'",
            "ВидДеятельности as \'Вид деятельности\'",
            "Часы as \'Часы\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("ГрафикE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    public class График : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private IIS.KR.Деятельность fВидДеятельности;
        
        private IIS.KR.КолвоЧасов fЧасы;
        
        private IIS.KR.Сотрудники fСотрудники;
        
        private IIS.KR.ГрафикРаботы fГрафикРаботы;
        
        // *** Start programmer edit section *** (График CustomMembers)

        // *** End programmer edit section *** (График CustomMembers)

        
        /// <summary>
        /// ВидДеятельности.
        /// </summary>
        // *** Start programmer edit section *** (График.ВидДеятельности CustomAttributes)

        // *** End programmer edit section *** (График.ВидДеятельности CustomAttributes)
        public virtual IIS.KR.Деятельность ВидДеятельности
        {
            get
            {
                // *** Start programmer edit section *** (График.ВидДеятельности Get start)

                // *** End programmer edit section *** (График.ВидДеятельности Get start)
                IIS.KR.Деятельность result = this.fВидДеятельности;
                // *** Start programmer edit section *** (График.ВидДеятельности Get end)

                // *** End programmer edit section *** (График.ВидДеятельности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.ВидДеятельности Set start)

                // *** End programmer edit section *** (График.ВидДеятельности Set start)
                this.fВидДеятельности = value;
                // *** Start programmer edit section *** (График.ВидДеятельности Set end)

                // *** End programmer edit section *** (График.ВидДеятельности Set end)
            }
        }
        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (График.Дата CustomAttributes)

        // *** End programmer edit section *** (График.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (График.Дата Get start)

                // *** End programmer edit section *** (График.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (График.Дата Get end)

                // *** End programmer edit section *** (График.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.Дата Set start)

                // *** End programmer edit section *** (График.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (График.Дата Set end)

                // *** End programmer edit section *** (График.Дата Set end)
            }
        }
        
        /// <summary>
        /// Часы.
        /// </summary>
        // *** Start programmer edit section *** (График.Часы CustomAttributes)

        // *** End programmer edit section *** (График.Часы CustomAttributes)
        public virtual IIS.KR.КолвоЧасов Часы
        {
            get
            {
                // *** Start programmer edit section *** (График.Часы Get start)

                // *** End programmer edit section *** (График.Часы Get start)
                IIS.KR.КолвоЧасов result = this.fЧасы;
                // *** Start programmer edit section *** (График.Часы Get end)

                // *** End programmer edit section *** (График.Часы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.Часы Set start)

                // *** End programmer edit section *** (График.Часы Set start)
                this.fЧасы = value;
                // *** Start programmer edit section *** (График.Часы Set end)

                // *** End programmer edit section *** (График.Часы Set end)
            }
        }
        
        /// <summary>
        /// График.
        /// </summary>
        // *** Start programmer edit section *** (График.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (График.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.KR.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (График.Сотрудники Get start)

                // *** End programmer edit section *** (График.Сотрудники Get start)
                IIS.KR.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (График.Сотрудники Get end)

                // *** End programmer edit section *** (График.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.Сотрудники Set start)

                // *** End programmer edit section *** (График.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (График.Сотрудники Set end)

                // *** End programmer edit section *** (График.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.KR.ГрафикРаботы.
        /// </summary>
        // *** Start programmer edit section *** (График.ГрафикРаботы CustomAttributes)

        // *** End programmer edit section *** (График.ГрафикРаботы CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ГрафикРаботы"})]
        public virtual IIS.KR.ГрафикРаботы ГрафикРаботы
        {
            get
            {
                // *** Start programmer edit section *** (График.ГрафикРаботы Get start)

                // *** End programmer edit section *** (График.ГрафикРаботы Get start)
                IIS.KR.ГрафикРаботы result = this.fГрафикРаботы;
                // *** Start programmer edit section *** (График.ГрафикРаботы Get end)

                // *** End programmer edit section *** (График.ГрафикРаботы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (График.ГрафикРаботы Set start)

                // *** End programmer edit section *** (График.ГрафикРаботы Set start)
                this.fГрафикРаботы = value;
                // *** Start programmer edit section *** (График.ГрафикРаботы Set end)

                // *** End programmer edit section *** (График.ГрафикРаботы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГрафикE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикE", typeof(IIS.KR.График));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of График.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfГрафик CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfГрафик CustomAttributes)
    public class DetailArrayOfГрафик : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.KR.DetailArrayOfГрафик members)

        // *** End programmer edit section *** (IIS.KR.DetailArrayOfГрафик members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type График by index.
        /// </summary>
        /// <summary>
        /// Adds object with type График.
        /// </summary>
        public DetailArrayOfГрафик(IIS.KR.ГрафикРаботы fГрафикРаботы) : 
                base(typeof(График), ((ICSSoft.STORMNET.DataObject)(fГрафикРаботы)))
        {
        }
        
        public IIS.KR.График this[int index]
        {
            get
            {
                return ((IIS.KR.График)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.KR.График dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
