//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// График работы.
    /// </summary>
    // *** Start programmer edit section *** (ГрафикРаботы CustomAttributes)

    // *** End programmer edit section *** (ГрафикРаботы CustomAttributes)
    [AutoAltered()]
    [Caption("График работы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ГрафикРаботыE", new string[] {
            "ДатаСоздания as \'Дата создания\'",
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.Должность as \'Должность\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [AssociatedDetailViewAttribute("ГрафикРаботыE", "График", "ГрафикE", true, "", "График", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ГрафикРаботыE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ГрафикРаботыL", new string[] {
            "ДатаСоздания as \'Дата создания\'",
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class ГрафикРаботы : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаСоздания = System.DateTime.Now;
        
        private IIS.KR.Сотрудники fСотрудники;
        
        private IIS.KR.DetailArrayOfГрафик fГрафик;
        
        // *** Start programmer edit section *** (ГрафикРаботы CustomMembers)

        // *** End programmer edit section *** (ГрафикРаботы CustomMembers)

        
        /// <summary>
        /// ДатаСоздания.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикРаботы.ДатаСоздания CustomAttributes)

        // *** End programmer edit section *** (ГрафикРаботы.ДатаСоздания CustomAttributes)
        public virtual System.DateTime ДатаСоздания
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикРаботы.ДатаСоздания Get start)

                // *** End programmer edit section *** (ГрафикРаботы.ДатаСоздания Get start)
                System.DateTime result = this.fДатаСоздания;
                // *** Start programmer edit section *** (ГрафикРаботы.ДатаСоздания Get end)

                // *** End programmer edit section *** (ГрафикРаботы.ДатаСоздания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикРаботы.ДатаСоздания Set start)

                // *** End programmer edit section *** (ГрафикРаботы.ДатаСоздания Set start)
                this.fДатаСоздания = value;
                // *** Start programmer edit section *** (ГрафикРаботы.ДатаСоздания Set end)

                // *** End programmer edit section *** (ГрафикРаботы.ДатаСоздания Set end)
            }
        }
        
        /// <summary>
        /// График работы.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикРаботы.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ГрафикРаботы.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.KR.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикРаботы.Сотрудники Get start)

                // *** End programmer edit section *** (ГрафикРаботы.Сотрудники Get start)
                IIS.KR.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ГрафикРаботы.Сотрудники Get end)

                // *** End programmer edit section *** (ГрафикРаботы.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикРаботы.Сотрудники Set start)

                // *** End programmer edit section *** (ГрафикРаботы.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ГрафикРаботы.Сотрудники Set end)

                // *** End programmer edit section *** (ГрафикРаботы.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// График работы.
        /// </summary>
        // *** Start programmer edit section *** (ГрафикРаботы.График CustomAttributes)

        // *** End programmer edit section *** (ГрафикРаботы.График CustomAttributes)
        public virtual IIS.KR.DetailArrayOfГрафик График
        {
            get
            {
                // *** Start programmer edit section *** (ГрафикРаботы.График Get start)

                // *** End programmer edit section *** (ГрафикРаботы.График Get start)
                if ((this.fГрафик == null))
                {
                    this.fГрафик = new IIS.KR.DetailArrayOfГрафик(this);
                }
                IIS.KR.DetailArrayOfГрафик result = this.fГрафик;
                // *** Start programmer edit section *** (ГрафикРаботы.График Get end)

                // *** End programmer edit section *** (ГрафикРаботы.График Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ГрафикРаботы.График Set start)

                // *** End programmer edit section *** (ГрафикРаботы.График Set start)
                this.fГрафик = value;
                // *** Start programmer edit section *** (ГрафикРаботы.График Set end)

                // *** End programmer edit section *** (ГрафикРаботы.График Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ГрафикРаботыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикРаботыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикРаботыE", typeof(IIS.KR.ГрафикРаботы));
                }
            }
            
            /// <summary>
            /// "ГрафикРаботыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ГрафикРаботыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ГрафикРаботыL", typeof(IIS.KR.ГрафикРаботы));
                }
            }
        }
    }
}
