//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Деятельность.
    /// </summary>
    // *** Start programmer edit section *** (Деятельность CustomAttributes)

    // *** End programmer edit section *** (Деятельность CustomAttributes)
    public enum Деятельность
    {
        
        // *** Start programmer edit section *** (Деятельность.Работает CustomAttributes)

        // *** End programmer edit section *** (Деятельность.Работает CustomAttributes)
        [Caption("Работает")]
        Работает,
        
        // *** Start programmer edit section *** (Деятельность.Отпуск CustomAttributes)

        // *** End programmer edit section *** (Деятельность.Отпуск CustomAttributes)
        [Caption("Отпуск")]
        Отпуск,
        
        // *** Start programmer edit section *** (Деятельность.Отгул CustomAttributes)

        // *** End programmer edit section *** (Деятельность.Отгул CustomAttributes)
        [Caption("Отгул")]
        Отгул,
        
        // *** Start programmer edit section *** (Деятельность.Больничный CustomAttributes)

        // *** End programmer edit section *** (Деятельность.Больничный CustomAttributes)
        [Caption("Больничный")]
        Больничный,
        
        // *** Start programmer edit section *** (Деятельность.Выходной CustomAttributes)

        // *** End programmer edit section *** (Деятельность.Выходной CustomAttributes)
        [Caption("Выходной")]
        Выходной,
    }
}
