//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Колво часов.
    /// </summary>
    // *** Start programmer edit section *** (КолвоЧасов CustomAttributes)

    // *** End programmer edit section *** (КолвоЧасов CustomAttributes)
    public enum КолвоЧасов
    {
        
        // *** Start programmer edit section *** (КолвоЧасов.Половина CustomAttributes)

        // *** End programmer edit section *** (КолвоЧасов.Половина CustomAttributes)
        [Caption("4")]
        Половина,
        
        // *** Start programmer edit section *** (КолвоЧасов.Восьми CustomAttributes)

        // *** End programmer edit section *** (КолвоЧасов.Восьми CustomAttributes)
        [Caption("8")]
        Восьми,
        
        // *** Start programmer edit section *** (КолвоЧасов.Двенадцати CustomAttributes)

        // *** End programmer edit section *** (КолвоЧасов.Двенадцати CustomAttributes)
        [Caption("12")]
        Двенадцати,
    }
}
