//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Найм работников.
    /// </summary>
    // *** Start programmer edit section *** (НаймРаботников CustomAttributes)

    // *** End programmer edit section *** (НаймРаботников CustomAttributes)
    [AutoAltered()]
    [Caption("Найм работников")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("НаймРаботниковE", new string[] {
            "ДатаНайма as \'Дата найма\'",
            "IDработника as \'I dработника\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Образование as \'Образование\'",
            "ОпытРаботы as \'Опыт работы\'",
            "Договор as \'Договор\'",
            "Вакансии as \'Вакансии\'",
            "Вакансии.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Вакансии.Наименование"})]
    [MasterViewDefineAttribute("НаймРаботниковE", "Вакансии", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("НаймРаботниковL", new string[] {
            "ДатаНайма as \'Дата найма\'",
            "IDработника as \'I dработника\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "Образование as \'Образование\'",
            "ОпытРаботы as \'Опыт работы\'",
            "Договор as \'Договор\'",
            "Вакансии.Наименование as \'Наименование\'"})]
    public class НаймРаботников : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДатаНайма;
        
        private int fIDработника;
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private IIS.KR.ВидОбразование fОбразование;
        
        private IIS.KR.Опыт fОпытРаботы;
        
        private IIS.KR.ВидДоговора fДоговор;
        
        private IIS.KR.Вакансии fВакансии;
        
        // *** Start programmer edit section *** (НаймРаботников CustomMembers)

        // *** End programmer edit section *** (НаймРаботников CustomMembers)

        
        /// <summary>
        /// IDработника.
        /// </summary>
        // *** Start programmer edit section *** (НаймРаботников.IDработника CustomAttributes)

        // *** End programmer edit section *** (НаймРаботников.IDработника CustomAttributes)
        public virtual int IDработника
        {
            get
            {
                // *** Start programmer edit section *** (НаймРаботников.IDработника Get start)

                // *** End programmer edit section *** (НаймРаботников.IDработника Get start)
                int result = this.fIDработника;
                // *** Start programmer edit section *** (НаймРаботников.IDработника Get end)

                // *** End programmer edit section *** (НаймРаботников.IDработника Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НаймРаботников.IDработника Set start)

                // *** End programmer edit section *** (НаймРаботников.IDработника Set start)
                this.fIDработника = value;
                // *** Start programmer edit section *** (НаймРаботников.IDработника Set end)

                // *** End programmer edit section *** (НаймРаботников.IDработника Set end)
            }
        }
        
        /// <summary>
        /// ДатаНайма.
        /// </summary>
        // *** Start programmer edit section *** (НаймРаботников.ДатаНайма CustomAttributes)

        // *** End programmer edit section *** (НаймРаботников.ДатаНайма CustomAttributes)
        public virtual System.DateTime ДатаНайма
        {
            get
            {
                // *** Start programmer edit section *** (НаймРаботников.ДатаНайма Get start)

                // *** End programmer edit section *** (НаймРаботников.ДатаНайма Get start)
                System.DateTime result = this.fДатаНайма;
                // *** Start programmer edit section *** (НаймРаботников.ДатаНайма Get end)

                // *** End programmer edit section *** (НаймРаботников.ДатаНайма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НаймРаботников.ДатаНайма Set start)

                // *** End programmer edit section *** (НаймРаботников.ДатаНайма Set start)
                this.fДатаНайма = value;
                // *** Start programmer edit section *** (НаймРаботников.ДатаНайма Set end)

                // *** End programmer edit section *** (НаймРаботников.ДатаНайма Set end)
            }
        }
        
        /// <summary>
        /// Договор.
        /// </summary>
        // *** Start programmer edit section *** (НаймРаботников.Договор CustomAttributes)

        // *** End programmer edit section *** (НаймРаботников.Договор CustomAttributes)
        public virtual IIS.KR.ВидДоговора Договор
        {
            get
            {
                // *** Start programmer edit section *** (НаймРаботников.Договор Get start)

                // *** End programmer edit section *** (НаймРаботников.Договор Get start)
                IIS.KR.ВидДоговора result = this.fДоговор;
                // *** Start programmer edit section *** (НаймРаботников.Договор Get end)

                // *** End programmer edit section *** (НаймРаботников.Договор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НаймРаботников.Договор Set start)

                // *** End programmer edit section *** (НаймРаботников.Договор Set start)
                this.fДоговор = value;
                // *** Start programmer edit section *** (НаймРаботников.Договор Set end)

                // *** End programmer edit section *** (НаймРаботников.Договор Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (НаймРаботников.Имя CustomAttributes)

        // *** End programmer edit section *** (НаймРаботников.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (НаймРаботников.Имя Get start)

                // *** End programmer edit section *** (НаймРаботников.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (НаймРаботников.Имя Get end)

                // *** End programmer edit section *** (НаймРаботников.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НаймРаботников.Имя Set start)

                // *** End programmer edit section *** (НаймРаботников.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (НаймРаботников.Имя Set end)

                // *** End programmer edit section *** (НаймРаботников.Имя Set end)
            }
        }
        
        /// <summary>
        /// Образование.
        /// </summary>
        // *** Start programmer edit section *** (НаймРаботников.Образование CustomAttributes)

        // *** End programmer edit section *** (НаймРаботников.Образование CustomAttributes)
        public virtual IIS.KR.ВидОбразование Образование
        {
            get
            {
                // *** Start programmer edit section *** (НаймРаботников.Образование Get start)

                // *** End programmer edit section *** (НаймРаботников.Образование Get start)
                IIS.KR.ВидОбразование result = this.fОбразование;
                // *** Start programmer edit section *** (НаймРаботников.Образование Get end)

                // *** End programmer edit section *** (НаймРаботников.Образование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НаймРаботников.Образование Set start)

                // *** End programmer edit section *** (НаймРаботников.Образование Set start)
                this.fОбразование = value;
                // *** Start programmer edit section *** (НаймРаботников.Образование Set end)

                // *** End programmer edit section *** (НаймРаботников.Образование Set end)
            }
        }
        
        /// <summary>
        /// ОпытРаботы.
        /// </summary>
        // *** Start programmer edit section *** (НаймРаботников.ОпытРаботы CustomAttributes)

        // *** End programmer edit section *** (НаймРаботников.ОпытРаботы CustomAttributes)
        public virtual IIS.KR.Опыт ОпытРаботы
        {
            get
            {
                // *** Start programmer edit section *** (НаймРаботников.ОпытРаботы Get start)

                // *** End programmer edit section *** (НаймРаботников.ОпытРаботы Get start)
                IIS.KR.Опыт result = this.fОпытРаботы;
                // *** Start programmer edit section *** (НаймРаботников.ОпытРаботы Get end)

                // *** End programmer edit section *** (НаймРаботников.ОпытРаботы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НаймРаботников.ОпытРаботы Set start)

                // *** End programmer edit section *** (НаймРаботников.ОпытРаботы Set start)
                this.fОпытРаботы = value;
                // *** Start programmer edit section *** (НаймРаботников.ОпытРаботы Set end)

                // *** End programmer edit section *** (НаймРаботников.ОпытРаботы Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (НаймРаботников.Отчество CustomAttributes)

        // *** End programmer edit section *** (НаймРаботников.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (НаймРаботников.Отчество Get start)

                // *** End programmer edit section *** (НаймРаботников.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (НаймРаботников.Отчество Get end)

                // *** End programmer edit section *** (НаймРаботников.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НаймРаботников.Отчество Set start)

                // *** End programmer edit section *** (НаймРаботников.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (НаймРаботников.Отчество Set end)

                // *** End programmer edit section *** (НаймРаботников.Отчество Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (НаймРаботников.Фамилия CustomAttributes)

        // *** End programmer edit section *** (НаймРаботников.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (НаймРаботников.Фамилия Get start)

                // *** End programmer edit section *** (НаймРаботников.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (НаймРаботников.Фамилия Get end)

                // *** End programmer edit section *** (НаймРаботников.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НаймРаботников.Фамилия Set start)

                // *** End programmer edit section *** (НаймРаботников.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (НаймРаботников.Фамилия Set end)

                // *** End programmer edit section *** (НаймРаботников.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Найм работников.
        /// </summary>
        // *** Start programmer edit section *** (НаймРаботников.Вакансии CustomAttributes)

        // *** End programmer edit section *** (НаймРаботников.Вакансии CustomAttributes)
        [PropertyStorage(new string[] {
                "Вакансии"})]
        [NotNull()]
        public virtual IIS.KR.Вакансии Вакансии
        {
            get
            {
                // *** Start programmer edit section *** (НаймРаботников.Вакансии Get start)

                // *** End programmer edit section *** (НаймРаботников.Вакансии Get start)
                IIS.KR.Вакансии result = this.fВакансии;
                // *** Start programmer edit section *** (НаймРаботников.Вакансии Get end)

                // *** End programmer edit section *** (НаймРаботников.Вакансии Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (НаймРаботников.Вакансии Set start)

                // *** End programmer edit section *** (НаймРаботников.Вакансии Set start)
                this.fВакансии = value;
                // *** Start programmer edit section *** (НаймРаботников.Вакансии Set end)

                // *** End programmer edit section *** (НаймРаботников.Вакансии Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "НаймРаботниковE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НаймРаботниковE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НаймРаботниковE", typeof(IIS.KR.НаймРаботников));
                }
            }
            
            /// <summary>
            /// "НаймРаботниковL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View НаймРаботниковL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("НаймРаботниковL", typeof(IIS.KR.НаймРаботников));
                }
            }
        }
    }
}
