//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.KR
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Опыт.
    /// </summary>
    // *** Start programmer edit section *** (Опыт CustomAttributes)

    // *** End programmer edit section *** (Опыт CustomAttributes)
    public enum Опыт
    {
        
        // *** Start programmer edit section *** (Опыт.Нет CustomAttributes)

        // *** End programmer edit section *** (Опыт.Нет CustomAttributes)
        [Caption("Нет")]
        Нет,
        
        // *** Start programmer edit section *** (Опыт.ДоГода CustomAttributes)

        // *** End programmer edit section *** (Опыт.ДоГода CustomAttributes)
        [Caption("ДоГода")]
        ДоГода,
        
        // *** Start programmer edit section *** (Опыт.ДоТлет CustomAttributes)

        // *** End programmer edit section *** (Опыт.ДоТлет CustomAttributes)
        [Caption("До3лет")]
        ДоТлет,
        
        // *** Start programmer edit section *** (Опыт.ДоПлет CustomAttributes)

        // *** End programmer edit section *** (Опыт.ДоПлет CustomAttributes)
        [Caption("До5лет")]
        ДоПлет,
        
        // *** Start programmer edit section *** (Опыт.ДоДлетиболее CustomAttributes)

        // *** End programmer edit section *** (Опыт.ДоДлетиболее CustomAttributes)
        [Caption("До10ЛетиБолее")]
        ДоДлетиболее,
    }
}
